title: Welcome to my Blog!
author: fuenfhausen
email: pete.fuenfhausen@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Just a little test blog to learn Github pages
theme: minima

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
